// Discovery, announcements, heads exchange, merge, disconnect, and profile (§5).
// Pending stubs, one per normative requirement, named by spec section. Each
// later stage turns its stubs into passing tests.

import { describe, test } from 'bun:test'

describe('network-protocol', () => {
  test.todo('§5.2 [MUST] the peer bootstraps from any one discovery mechanism alone', () => {})
  test.todo('§5.2 [MUST] content-network native discovery is supported', () => {})
  test.todo('§5.3.1 [MUST] peers publish and subscribe to topic RECORD, bytes 52 45 43 4f 52 44', () => {})
  test.todo('§5.3.1 [MUST] a library topic too long for the pubsub runtime surfaces an error instead of truncating or hashing', () => {})
  test.todo('§5.3.2 [vector] F6 LoadedAboutEntry inlines the about payload and serialises to 1060 bytes', () => {})
  test.todo('§5.3.2 [MUST] announcements are JSON-encoded and published via pubsub', () => {})
  test.todo('§5.3.2 [MUST] an announced about entry is authenticated only after re-fetching the canonical entry by hash', () => {})
  test.todo('§5.3.2 [MUST] announcements over 256 KiB of JSON are not sent', () => {})
  test.todo('§5.3.2 [MUST] received announcements over 256 KiB are dropped unprocessed', () => {})
  test.todo('§5.3.2 [MUST] announcement content is an untrusted hint until the AC chain and signatures verify', () => {})
  test.todo('§5.3.3 [MUST] at most one announcement per RECORD peer-join per 5 seconds per target peer', () => {})
  test.todo('§5.3.3 [MUST] library state changes are not re-announced on RECORD', () => {})
  test.todo('§5.3.3 [MUST] a missing announcement is not taken to mean the library does not exist', () => {})
  test.todo('§5.4.1 [vector] the single-entry heads message is the 122-byte spec JSON', () => {})
  test.todo('§5.4.1 [MUST] each heads element is the base58btc CID of a current head', () => {})
  test.todo('§5.4.1 [MUST] heads are published on first subscribing to the library topic', () => {})
  test.todo('§5.4.1 [MUST] heads are published when a new peer joins the topic', () => {})
  test.todo('§5.4.1 [MUST] heads are published when the local heads set changes', () => {})
  test.todo('§5.4.1 [MUST] heads are published at most once per 1000 ms per library', () => {})
  test.todo('§5.4.1 [MUST] simultaneous heads triggers coalesce into one message', () => {})
  test.todo('§5.4.1 [MUST] a heads message does not exceed 256 KiB of JSON', () => {})
  test.todo('§5.4.1 [MUST] an oversized heads set splits across messages from the same trigger', () => {})
  test.todo('§5.4.1 [MUST] every split heads message but the last carries incomplete: true', () => {})
  test.todo('§5.4.1 [MUST] receivers treat a split batch as complete only after the message without incomplete: true', () => {})
  test.todo('§5.4.3 [MUST] incremental merge batches never include entries with unfetched ancestors', () => {})
  test.todo('§5.4.3 [MUST] concurrent heads messages for one library end in a state equal to some sequential merge order', () => {})
  test.todo('§5.4.3 [MUST] parallelised merges uphold the §4.5 invariants', () => {})
  test.todo('§5.4.4 [MUST] replication pauses for one library without closing its log', () => {})
  test.todo('§5.4.4 [MUST] pause stops heads publishing and new fetch tasks while in-flight fetches finish or time out', () => {})
  test.todo('§5.4.4 [MUST] entries in flight at pause are recorded as unresolved', () => {})
  test.todo('§5.4.4 [MUST] resume re-enters traversal for unresolved entries before publishing heads', () => {})
  test.todo('§5.4.4 [MUST] resume does not re-fetch entries that already landed', () => {})
  test.todo('§5.4.5 [MUST] heads referencing unfetchable CIDs are tolerated', () => {})
  test.todo('§5.4.5 [MUST] a per-entry timeout does not stall the replicator', () => {})
  test.todo('§5.4.5 [MUST] an unreachable library keeps its local oplog', () => {})
  test.todo('§5.4.5 [MUST] fetch failures never emit a library-removed signal', () => {})
  test.todo('§5.5 [MUST] the peer implements the §5.5.1 libp2p profile', () => {})
  test.todo('§5.5.1 [MUST] the pubsub router is gossipsub', () => {})
  test.todo('§5.5.1 [MUST] the swarm uses the Record pre-shared key', () => {})
})
